name: "GitRag Indexer"
description: "Run the GitRag indexing CLI for libSQL or PostgreSQL"
inputs:
  repo:
    description: "Repository identifier (namespace/name)"
    required: true
  db_provider:
    description: "Database provider ('libsql' or 'postgres')"
    required: false
    default: "libsql"
  database_url:
    description: "Connection URL (Include username for Postgres: postgresql://user@host/db)"
    required: true
  db_auth_token:
    description: "Password or Auth Token"
    required: true
  full_index:
    description: "Set to true to index all tracked files"
    required: false
    default: "false"
  branch:
    description: "Branch name"
    required: false

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    
    - name: Install dependencies
      shell: bash
      run: python -m pip install -r ${{ github.action_path }}/requirements.txt

    - name: Run Indexer
      shell: bash
      env:
        DB_PROVIDER: ${{ inputs.db_provider }}
        DATABASE_URL: ${{ inputs.database_url }}
        DB_AUTH_TOKEN: ${{ inputs.db_auth_token }}
        PYTHONPATH: ${{ github.action_path }}/packages/core/src
      run: |
        ARGS=""
        [ "${{ inputs.full_index }}" = "true" ] && ARGS="--full"
        [ -n "${{ inputs.branch }}" ] && ARGS="$ARGS --branch ${{ inputs.branch }}"
        
        # If not a full scan, pass the commit range
        if [ "${{ inputs.full_index }}" != "true" ]; then
          BEFORE="${{ github.event.before }}"
          if [ -n "$BEFORE" ] && [ "$BEFORE" != "0000000000000000000000000000000000000000" ]; then
            ARGS="$ARGS --from-sha $BEFORE --to-sha ${{ github.sha }}"
          fi
        fi
        python ${{ github.action_path }}/packages/core/src/Indexer.py "${{ inputs.repo }}" $ARGS
